import turtle
turtle.setup(400,300)
window=turtle.Screen()
window.title("Square window")
the_turtle=turtle.getturtle()
the_turtle.forward(100)
the_turtle.left(90)
the_turtle.forward(100)
the_turtle.left(90)
the_turtle.forward(100)
the_turtle.left(90)
the_turtle.forward(100)
the_turtle.left(90)
turtle.done()
