import turtle
turtle.width(3)
turtle.color('blue')
turtle.circle(20)
turtle.penup()
turtle.forward(45)
turtle.pendown()
turtle.color('black')
turtle.circle(20)
turtle.penup()
turtle.forward(45)
turtle.pendown()
turtle.color('red')
turtle.circle(20)
turtle.penup()
turtle.forward(45)
turtle.pendown()
turtle.penup()
turtle.right(180)
turtle.forward(135)
turtle.left(90)
turtle.forward(25)
turtle.left(90)
turtle.forward(20)
turtle.pendown()
turtle.color('yellow')
turtle.circle(20)
turtle.penup()
turtle.forward(45)
turtle.pendown()
turtle.color('green')
turtle.circle(20)
turtle.penup()
turtle.forward(45)
turtle.pendown()

turtle.exitonclick()

